server:
  port: 9001
spring:
  application:
    name: hello-feign-consume
eureka:
  instance:
    hostname: consume_feign
    prefer-ip-address: true
    instance-id: consume_feign
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
