server:
  port: 8003
spring:
  application:
    name: hello-service
eureka:
  instance:
    hostname: service_8003
    prefer-ip-address: true
    instance-id: service_8003
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
